// Generated by CIRCT firtool-1.37.0
module Queue(
  input        clock,
               reset,
               io_enq_valid,
  input  [7:0] io_enq_bits_sData,
  input  [3:0] io_enq_bits_sdest,
  input        io_deq_ready,
  output       io_enq_ready,
               io_deq_valid,
  output [7:0] io_deq_bits_sData,
  output [3:0] io_deq_bits_sdest
);

  reg  [11:0] ram;
  reg         maybe_full;
  wire        do_enq = ~maybe_full & io_enq_valid;
  always @(posedge clock) begin
    if (do_enq)
      ram <= {io_enq_bits_sdest, io_enq_bits_sData};
    if (reset)
      maybe_full <= 1'h0;
    else if (do_enq != (io_deq_ready & maybe_full))
      maybe_full <= do_enq;
  end // always @(posedge)
  assign io_enq_ready = ~maybe_full;
  assign io_deq_valid = maybe_full;
  assign io_deq_bits_sData = ram[7:0];
  assign io_deq_bits_sdest = ram[11:8];
endmodule

