// Generated by CIRCT firtool-1.37.0
module RingCrossbar(
  input        clock,
               reset,
               in_0_valid,
  input  [7:0] in_0_bits,
  input        in_1_valid,
  input  [7:0] in_1_bits,
  input        in_2_valid,
  input  [7:0] in_2_bits,
  input        in_3_valid,
  input  [7:0] in_3_bits,
  input  [3:0] dest_0,
               dest_1,
               dest_2,
               dest_3,
  input        out_0_ready,
               out_1_ready,
               out_2_ready,
               out_3_ready,
  output       in_0_ready,
               in_1_ready,
               in_2_ready,
               in_3_ready,
               out_0_valid,
  output [7:0] out_0_bits,
  output       out_1_valid,
  output [7:0] out_1_bits,
  output       out_2_valid,
  output [7:0] out_2_bits,
  output       out_3_valid,
  output [7:0] out_3_bits
);

  wire       _st_2_ringDataOut_ready;
  wire       _st_2_ringDataOut_valid;
  wire [7:0] _st_2_ringDataOut_bits_sData;
  wire [3:0] _st_2_ringDataOut_bits_sdest;
  wire       _st_1_ringDataOut_ready;
  wire       _st_1_ringDataOut_valid;
  wire [7:0] _st_1_ringDataOut_bits_sData;
  wire [3:0] _st_1_ringDataOut_bits_sdest;
  wire       _st_0_ringDataIn_valid;
  wire [7:0] _st_0_ringDataIn_bits_sData;
  wire [3:0] _st_0_ringDataIn_bits_sdest;
  wire       _st_0_ringDataOut_ready;
  wire       _st_0_ringDataIn_ready;
  wire       _st_0_ringDataOut_valid;
  wire [7:0] _st_0_ringDataOut_bits_sData;
  wire [3:0] _st_0_ringDataOut_bits_sdest;
  Station st_0 (
    .clock                  (clock),
    .reset                  (reset),
    .in_valid               (in_0_valid),
    .in_bits                (in_0_bits),
    .dest                   (dest_0),
    .out_ready              (out_0_ready),
    .ringDataIn_valid       (_st_0_ringDataIn_valid),
    .ringDataIn_bits_sData  (_st_0_ringDataIn_bits_sData),
    .ringDataIn_bits_sdest  (_st_0_ringDataIn_bits_sdest),
    .ringDataOut_ready      (_st_0_ringDataOut_ready),
    .in_ready               (in_0_ready),
    .out_valid              (out_0_valid),
    .out_bits               (out_0_bits),
    .ringDataIn_ready       (_st_0_ringDataIn_ready),
    .ringDataOut_valid      (_st_0_ringDataOut_valid),
    .ringDataOut_bits_sData (_st_0_ringDataOut_bits_sData),
    .ringDataOut_bits_sdest (_st_0_ringDataOut_bits_sdest)
  );
  Station_1 st_1 (
    .clock                  (clock),
    .reset                  (reset),
    .in_valid               (in_1_valid),
    .in_bits                (in_1_bits),
    .dest                   (dest_1),
    .out_ready              (out_1_ready),
    .ringDataIn_valid       (_st_0_ringDataOut_valid),
    .ringDataIn_bits_sData  (_st_0_ringDataOut_bits_sData),
    .ringDataIn_bits_sdest  (_st_0_ringDataOut_bits_sdest),
    .ringDataOut_ready      (_st_1_ringDataOut_ready),
    .in_ready               (in_1_ready),
    .out_valid              (out_1_valid),
    .out_bits               (out_1_bits),
    .ringDataIn_ready       (_st_0_ringDataOut_ready),
    .ringDataOut_valid      (_st_1_ringDataOut_valid),
    .ringDataOut_bits_sData (_st_1_ringDataOut_bits_sData),
    .ringDataOut_bits_sdest (_st_1_ringDataOut_bits_sdest)
  );
  Station_2 st_2 (
    .clock                  (clock),
    .reset                  (reset),
    .in_valid               (in_2_valid),
    .in_bits                (in_2_bits),
    .dest                   (dest_2),
    .out_ready              (out_2_ready),
    .ringDataIn_valid       (_st_1_ringDataOut_valid),
    .ringDataIn_bits_sData  (_st_1_ringDataOut_bits_sData),
    .ringDataIn_bits_sdest  (_st_1_ringDataOut_bits_sdest),
    .ringDataOut_ready      (_st_2_ringDataOut_ready),
    .in_ready               (in_2_ready),
    .out_valid              (out_2_valid),
    .out_bits               (out_2_bits),
    .ringDataIn_ready       (_st_1_ringDataOut_ready),
    .ringDataOut_valid      (_st_2_ringDataOut_valid),
    .ringDataOut_bits_sData (_st_2_ringDataOut_bits_sData),
    .ringDataOut_bits_sdest (_st_2_ringDataOut_bits_sdest)
  );
  Station_3 st_3 (
    .clock                  (clock),
    .reset                  (reset),
    .in_valid               (in_3_valid),
    .in_bits                (in_3_bits),
    .dest                   (dest_3),
    .out_ready              (out_3_ready),
    .ringDataIn_valid       (_st_2_ringDataOut_valid),
    .ringDataIn_bits_sData  (_st_2_ringDataOut_bits_sData),
    .ringDataIn_bits_sdest  (_st_2_ringDataOut_bits_sdest),
    .ringDataOut_ready      (_st_0_ringDataIn_ready),
    .in_ready               (in_3_ready),
    .out_valid              (out_3_valid),
    .out_bits               (out_3_bits),
    .ringDataIn_ready       (_st_2_ringDataOut_ready),
    .ringDataOut_valid      (_st_0_ringDataIn_valid),
    .ringDataOut_bits_sData (_st_0_ringDataIn_bits_sData),
    .ringDataOut_bits_sdest (_st_0_ringDataIn_bits_sdest)
  );
endmodule

